// Generated by CoffeeScript 1.11.1
(function() {
  var sequencer;

  sequencer = require('./sequence');

  module.exports = (function(_this) {
    return function() {
      var result;
      setInterval((function() {}), 10000);
      result = {
        sequence: function() {
          return sequencer(result);
        }
      };
      return result;
    };
  })(this);

}).call(this);
